### PR TITLE
Another Pull Request

### PR DESCRIPTION
**Pull request by Belias02**
*Changes the name of Balrog to Durin's Bane.
*Changes the +200% of gandalf to +50%
*Erase the must set Up to attack of saruman (since is not a siege unit)
*Adds the Great Library Icon as the Great Archive (I didn't do the atlas)

### CODE REVIEW

**Comment by RealBamboolord** [comment]
I personally don't like the change of Saruman and Gandalf, I don't want to change original design too much.
Renaming the Balrog has sprite issues, I don't like having that. Also, not every player may be familiar with the name Durin's Bane

**Comment by Belias02** [comment]
Ok. Do I make another pull request with more balanced heroes? Because as it is good heroes are stronger than evil ones

**Comment by RealBamboolord** [comment]
Not all but needs to be done at some point

**Comment by RealBamboolord** [comment]
Feel free to propose balance changes

**Pull request closed without merging**
